spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/ms-user
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

server:
  port: 8081

broker:
  queue:
    email:
      name: default.email.queue